[package]
name = "ops-tools"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["read-excel"]

[workspace.dependencies]
read-excel = { path = "./read-excel"}
calamine = "0.33.0"

[dependencies]
read-excel = { workspace = true }